
stages:
  - test
  - build


.build-docker-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind

  variables:
    REGISTRY_HOST: eu.gcr.io
    IMAGE_NAME: $REGISTRY_HOST/$GCP_PROJECT/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH

  before_script:
    # see https://cloud.google.com/container-registry/docs/advanced-authentication#json-key
    - cat $GITLAB_REGISTRY_KEY | docker login  -u _json_key --password-stdin $REGISTRY_HOST

  script:
    - docker build --pull -t $IMAGE_NAME .
    - docker push $IMAGE_NAME


unit-test:
  image: python:3.8.1
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install -e .
    - pytest chaos/test/unit