
stages:
  - test
  - build

build-docker-image:
  stage: build
  image: docker:latest
  services:
  - docker:20.10.16-dind
  
  variables:
    REGISTRY_HOST: registry.gitlab.com
    IMAGE_NAME: $CI_REGISTRY/yotta-academy/mle-bootcamp/projects/ml-prod-projects/project-3-fall-2022/chaos-1/churn_app

  before_script:
    - echo "$CI_DEPLOY_PASSWORD"  | docker login $REGISTRY_HOST --username $CI_DEPLOY_USER --password-stdin

  # TODO : login to docker registry
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME



    
unit-test:
  image: python:3.8.1
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install -e .
    - pytest chaos/test/unit
