version: "3.8"
services:

  db:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5442:5432"

  api:
    build: .
    image: "eu.gcr.io/coyotta-2022/chaos-1:$SHORT_SHA"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/app/proxy/gcp_key.json
      - PYTHONPATH=/usr/app/
    volumes:
      - ./chaos/infrastructure/config/config.yml:/usr/app/chaos/infrastructure/config/config.yml
      - $GOOGLE_APPLICATION_CREDENTIALS:/usr/app/proxy/gcp_key.json
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data:
