version: "3.8"
services:

  db:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi

  api:
    build: .
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db/fastapi"
    ports:
      - "5000:8000"
    depends_on:
      - db

volumes:
  db-data: