version: "3.8"
services:

  db:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5442:5432"

  api:
    build: .
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/app/proxy/gcp_key.json
    volumes:
      - ./chaos/infrastructure/config/config.yml:/usr/app/chaos/infrastructure/config/config.yml
      - ./proxy/gcp_key.json:/usr/app/proxy/gcp_key.json
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data:
