apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-1-deployment
  labels:
    environment: develop
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: chaos-1-deployment
  template: 
    metadata:
      labels:
        app: chaos-1-deployment
    spec:
      volumes:
      - name: chaos-secrets-1
        secret:
          secretName: chaos-secrets-1
      containers:
      - name: churn-api
        image: eu.gcr.io/coyotta-2022/chaos-1:52c732c7
        imagePullPolicy: Always
        volumeMounts:
        - name: chaos-secrets-1
          mountPath: /secrets
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/key.json
        - name: YOTTA_ML3_CONFIGURATION_PATH
          value: /secrets/config.yml
      # adapted from https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine#service-account-key
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.33.1
        command:
          - "/cloud_sql_proxy"
          - "-log_debug_stdout"
          - "-instances=coyotta-2022:europe-west1:ml-prod-coyotta-2022-group-1-sql-16760197=tcp:5432"
          - "-credential_file=/secrets/key.json"
        securityContext:
          runAsNonRoot: true
        volumeMounts:
        -
          name: chaos-secrets-1
          mountPath: /secrets/
          readOnly: true
