apiVersion: v1
kind: Service
metadata:
  name: chaos-1-load-balancer
spec:
  selector:
    app: chaos-1-deployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer

